# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Update Details' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Update Details
pod 'Firebase/Database'

  target 'Update DetailsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Update DetailsUITests' do
    # Pods for testing
  end

end
